### ISSUE TITLE
CallOperatorWriteNode ergonomics for interpretation

### ISSUE THREAD

**Issue by enebo** [ruby/yarp#1236]
This node captures all the info needed to interpret this properly but it is not so simple to use.  If I have:

```ruby
a.b += c
```

We get:

```text
#<YARP::ParseResult:0x00007f7a624986b0
 @comments=[],
 @errors=[],
 @source=#<YARP::Source:0x00007f7a623e92f0 @offsets=[0], @source="a.b += c">,
 @value=
  ProgramNode(0...8)(
    [],
    StatementsNode(0...8)(
      [CallOperatorWriteNode(0...8)(
         CallNode(0...3)(
           CallNode(0...1)(nil, nil, (0...1), nil, nil, nil, nil, 2, "a"),
           (1...2),
           (2...3),
           nil,
           nil,
           nil,
           nil,
           0,
           "b="
         ),
         (4...6),
         CallNode(7...8)(nil, nil, (7...8), nil, nil, nil, nil, 2, "c"),
         :+
       )]
    )
  ),
 @warnings=[]>
```

In Ruby pseudo-ish code we need to do:

```text
%t1 = a
%t2 = %t1.b()
%t3 = %t2.+(c)
           %t1.b=(%t3)
```

We only call ```a``` once.  If we look up at the AST we currently have we need to do three somewhat non-obvious things:

  1. get target call node then get its receiver and call that once.
  2. get target call node but do not call ```b=``` but instead call ```b```.
  3. then when we do call ```b=``` we need to use value from 1.

This is obviously possible but I wonder if we could do it more like JRuby?  In JRuby we record this as (and I suspect this is same layout as MRI):

```text
 jruby -S ast -e 'a.b += 2'
AST:
RootNode line: 0
  OpAsgnNode* line: 0, variable_name: b, variable_assign_name: b=, operatorName: +
    VCallNode:a line: 0
    FixnumNode line: 0, long: 2
```

Is it possible to do something closer to this?  digging around in target feels less clear for interpretation but I also wonder how this looks to syntax tools since "b=" does not exist anywhere in the source.

note: in writing this up I realize how bad those fields names are: variable_name and variable_assign_name so please use better names if we do change this.

**Comment by eregon** [comment]
Agreed. I also discussed this and variants in https://github.com/ruby/yarp/pull/997.
I think it would be a good time to come back to that and make the nodes for ||=, &&= and += easier to use and avoiding the full matrix of combinations.

**Comment by eregon** [comment]
Specifically I think the representation in https://github.com/ruby/yarp/pull/997#issuecomment-1600563384 or similar would be convenient. Specifically it contains both the "read" call and "write" call nodes, which makes it super convenient to process (having to map from read to write or vice-versa is pretty messy, I think it's very nice if we don't need to do that when compiling the AST).
It also relates to https://github.com/ruby/yarp/issues/1143, we should have a special node to mean the value is provided by the runtime and there is no way to express it as a regular node in a semantically-correct way.

Or we could all the way and desugar all of these and introduce temporary variables in YARP. We probably would still want to wrap these 3 cases so e.g. special nodes can be used for ||=, etc. But temporary variables feel wrong for non-execute use cases and they can have more overhead than other ways of dealing with such temporary value (e.g. could be stored in a Java local variable in TruffleRuby which is cheaper than a FrameSlot).

**Comment by enebo** [comment]
@eregon the read + write node is probably the simplest to implement but I would like the serialized size to be as small as possible without hindering things.  I think just recording target node, value node, and methods names is smaller than what it currently is but it is also simpler to implement.

**Comment by eregon** [comment]
That would work but I think it'd be less convenient to process both for execution and analysis.
In `a.b += c` there is `a.b`, it seems really nice if that is part of the AST.
I see your point about serialized size but I think we're already pretty good there, much smaller than Ruby source code and yet we haven't even removed locations yet.

**Comment by enebo** [comment]
@eregon you mean less convenient than now or your idea to add additional callnodes to the AST?  My main problem with this now is having to dig into a call for its receiver and only call it once then save that value then call a different method on it.  I have no problems with my suggestion because both JRuby and MRI have been modelling it this way forever:

```text
 body: (OP_ASGN2@1:0-1:8 (VCALL@1:0-1:1 :a) false :b :+ (VCALL@1:7-1:8 :c)))
```

I think there is added value here just following other solutions because it is less mental translation.  Your read and write callnodes wrinkles my nose a bit because if this is a syntax tree then how do adding additional calls translate to syntax?  I am not saying we need a pure syntax AST but the dual-purpose of this gem always makes me think we should be biasing towards syntax over syntax since it still needs to parse syntax.

I don't think the size point is verifiable yet.  I think we are still consuming locations for interpretation so we are still pinned to the source.  Personally, I do think it will be smaller but it is hard for me to say it will be true at this point.

**Comment by eregon** [comment]
> @eregon you mean less convenient than now or your idea to add additional callnodes to the AST?

That it would be more convenient with additional callnodes in the AST.

When looking at [this comment](https://github.com/ruby/yarp/pull/997#issuecomment-1597044892) and [the next one](https://github.com/ruby/yarp/pull/997#issuecomment-1597061674) we can see the JRuby AST desugars += fully and there is both a read node and write node for `||=` and `&&=`, for variables and constants.
This is so nice, and it means there is no need for `InstanceVariableOperatorAndWriteNode` etc.
I think it would a be a great win for basically every usage of YARP if YARP does the same.

The only trouble is when calls are involved and not variables/constants, because there indeed we have the problem to not execute the LHS receiver twice. I feel like being as close as possible to the variable/constant case, notably having both the read and write nodes is nice. And then the only difference is the receiver of the write call node is `null`.

But it doesn't have to be like that, I think just having the `receiver`, `operator name`, `value` as you propose and let the user create relevant call nodes with that is fine too. It won't be as convenient though if e.g. one wants to analyze all call sites in some Ruby file.

Concretely, I would suggest to:
* do exactly the same as JRuby AST for &&=/||= on variables/constants, so OperatorAndAssignmentNode and OperatorOrAssignmentNode which contain both a read node and a write node.
* do the same as JRuby AST for += on variables/constants, that is desugar completely. I think it's fine/good to have an extra wrapper node around to have extra information relevant for syntax. Or if desugaring doesn't work well for YARP, then this case could use a OperatorAssignmentNode, with both a read node and write node.

And for calls we could do the same, just having the receiver of the write node be `null`.

**Comment by enebo** [comment]
@eregon I can generically say anything being done the same way as JRuby today will not be a problem for me...but...I opened this issue specifically because I ran into it first.  The others may have issues but you are trying to expand the scope of what I am trying to address.    This makes what might be a simpler change into a much broader discussion on a whole class of nodes (in which you already did not win the last round of arguments about it).

Don't take that too negatively I may open up another issue today on one of the other nodes.  Or this issue might convince some others that the others nodes should be reconsidered as a result.  I just find the case of receiver being special (e.g. it can only get called once) worthy of being its own issue.
