### ISSUE TITLE
Numerics have a flag for base

### ISSUE THREAD

**Issue by jemmaissroff** [ruby/yarp#1429]
Numeric nodes should expose their base via a flag

**Comment by eregon** [comment]
How do you use this flag/why do you need it?
Is this necessary if we expose the integer value as a field? (#1098)

I think this does increase footprint for information that can fairly trivially be accessed in other ways, i.e. looking at the start of the node location like https://github.com/oracle/truffleruby/blob/260d07b79a5c825e2ca39d0241c0cea64641be5d/src/main/java/org/truffleruby/parser/YARPTranslator.java#L875-L901
All of that logic can go away once we have #1098 done.

**Comment by kddnewton** [comment]
We're going to use it to pass through to the `rb_cstr_to_inum` function.

It doesn't increase the memory footprint of the C code, and only increases the serialized form by 1 byte per integer. This seems like a good addition to avoid having to reparse/the potential for bugs. For example, it looks like TruffleRuby is not currently accounting for negatives.

This logic can't go away once #1098 is done because for values outside of the 2^32 range, it's still going to be necessary.

**Comment by eregon** [comment]
It looks like `rb_cstr_to_inum()` can be passed `base=0` and then it automatically detects the base:
https://github.com/ruby/ruby/blob/b55785579cf114acbb0d9809b9e429d31b7aa8f3/include/ruby/internal/intern/bignum.h#L100-L125
And therefore this flag is not necessary for calling `rb_cstr_to_inum()` (these semantics need to intrinsically exist anyway for `Kernel#Integer()`)
