### ISSUE TITLE
Request for way to know omitted hash value type

### ISSUE THREAD

**Issue by tompng** [ruby/yarp#1447]
For hash value omission like `{ lvar: }`, `{ method: }`, `{ A: }`, I want to know the type of omitted value.

```ruby
YARP.parse("a=1;{a:}").value.statements.body[1]
# => HashNode(4...8)((4...5), [AssocNode(5...7)(SymbolNode(5...7)(nil, (5...6), (6...7), "a"), nil, nil)], (7...8))
YARP.parse("b=1;{a:}").value.statements.body[1]
# => HashNode(4...8)((4...5), [AssocNode(5...7)(SymbolNode(5...7)(nil, (5...6), (6...7), "a"), nil, nil)], (7...8))
```

For RubyVM::AST, it can be distinguished by `LVAR` `VCALL`.
```ruby
RubyVM::AbstractSyntaxTree.parse "a=1;{a:}"
# => 
(SCOPE@1:0-1:8
 tbl: [:a]
 args: nil
 body: (BLOCK@1:0-1:8 (LASGN@1:0-1:3 :a (LIT@1:2-1:3 1)) (HASH@1:4-1:8 (LIST@1:5-1:7 (LIT@1:5-1:7 :a) (LVAR@1:5-1:7 :a) nil))))

RubyVM::AbstractSyntaxTree.parse "b=1;{a:}"
# => 
(SCOPE@1:0-1:8
 tbl: [:b]
 args: nil
 body: (BLOCK@1:0-1:8 (LASGN@1:0-1:3 :b (LIT@1:2-1:3 1)) (HASH@1:4-1:8 (LIST@1:5-1:7 (LIT@1:5-1:7 :a) (VCALL@1:5-1:7 :a) nil))))

# Difference: (LVAR@1:5-1:7 :a) vs (VCALL@1:5-1:7 :a)
```

**Comment by eregon** [comment]
I think this could be provided by the [DesugarVisitor](https://github.com/ruby/yarp/blob/main/lib/yarp/desugar_visitor.rb), which would give the proper value node for `AssocNode`.
But the information would need to be preserved somehow, because it sounds quite messy to track local variables in DesugarVisitor.
Maybe a flag on AssocNode?

Or maybe these should always be desugared, but have a flag on AssocNode to know whether the value is part of the source or was omitted?

(I didn't know one can use `{a:}` and that calls method `a`, seems a bit too magic for a literal to call a method without a clear method call there)

**Comment by kddnewton** [comment]
@tompng thanks for the report - we'll add a flag for this

**Comment by kddnewton** [comment]
Actually not, because we'll additionally need the depth. This might be more complicated, I'll look into this today.

**Comment by eregon** [comment]
This feels like a case that would be a lot easier to handle if it is always desugared, and then it has an obvious representation with all the necessary information.
Then we'd just need some way to denote that the value is not present in the source, it could be a location of offset 0 length 0 or a flag or a wrapping node (not so great for footprint), etc.
