### ISSUE TITLE
Return error for incorrect usage of break, next, retry, and redo keywords

### ISSUE THREAD

**Issue by andrykonchin** [ruby/yarp#913]
CRuby raises `SyntaxError` when such keywords are used in improper context:

```ruby
def foo
  break 42
end
# => Invalid break (SyntaxError)

def foo
  next
end
# => Invalid next (SyntaxError)

def foo
  retry
end
# => Invalid retry (SyntaxError)

def foo
  redo
end
# => Invalid redo (SyntaxError)
```

But YARP right now doesn't return errors, e.g.

```
bin/parse -e "def foo; retry; end"
#<YARP::ParseResult:0x000000010cc2ed38
 @comments=[],
 @errors=[],
 @value=
  ProgramNode(0...19)(
    ScopeNode(0...0)([]),
    StatementsNode(0...19)(
      [DefNode(0...19)(
         IDENTIFIER(4...7)("foo"),
         nil,
         nil,
         StatementsNode(9...14)([RetryNode(9...14)()]),
         ScopeNode(0...3)([]),
         (0...3),
         nil,
         nil,
         nil,
         nil,
         (16...19)
       )]
    )
  ),
 @warnings=[]>
```

**Comment by eregon** [comment]
I think it'd be good if YARP can parse those, because it would be more correct for lazy method translation, i.e., with lazy method translation we would only get this error when executing that method, which is later than CRuby currently.
Having the error earlier seems better for all (except it would need extra checks in YARP).

So in general I think it's best if all/as-much-as-possible SyntaxError are raised during parsing, not later, both because it's more intuitive and also more compatible when doing lazy method translation.

**Comment by kddnewton** [comment]
I don't think we properly handle this in the parser without significant bookkeeping. Consider:

```ruby
def foo
  eval("yield 1")
end

foo { p _1 }
```

The only way we can properly give an error in this case would be for the calling library to pass in all possible parent scopes in some structure that we then interpret.

Even outside the `eval` use case, it would require effectively compiling the AST by walking up the context stack to find loops/methods/etc. to determine the kind of labels to jump to to tell if it's valid. This seems well beyond the scope of the parser, and sits quite well within the scope of a compiler.

**Comment by eregon** [comment]
I think for these we would need to know if we are inside a block or `while` loop (then those keywords are valid) or not (then SyntaxError).
(for `retry` I think it's about inside a `rescue` vs not, that's slightly different)
@kddnewton  Doesn't YARP know that or can trivially know that when parsing?

Of course `eval` is out of scope for parsing the whole snippet.
And when using YARP to parse eval's then yes I expect it makes a difference whether there is a single outer scope (so we are not parsing inside a block but inside a `def` method/module body/top-level) or multiple outer scopes (we are parsing inside a block).

> The only way we can properly give an error in this case would be for the calling library to pass in all possible parent scopes in some structure that we then interpret.

We already do that via https://github.com/ruby/yarp/blob/main/docs/serialization.md#apis, isn't it?

But indeed right now YARP doesn't know if an `eval` is inside a `while` loop, *but* break is not allowed inside eval anyway (and YARP knows we are inside an eval if there is 1+ scopes in metadata):
```
$ ruby -e 'while true; eval "break"; end'
(eval): (eval):1: Can't escape from eval with break (SyntaxError)

$ ruby -e 'while true; eval "next"; end' 
(eval): (eval):1: Can't escape from eval with next (SyntaxError)

$ ruby -e 'while true; eval "redo"; end'
(eval): (eval):1: Can't escape from eval with redo (SyntaxError)

$ ruby -e 'while true; eval "retry"; end'
(eval): (eval):1: Invalid retry (SyntaxError)
```

**Comment by enebo** [comment]
`eval` is not worth talking about since we cannot know the contents or whether it will ever execute.    Let's just focus on lazy methods in concrete syntax.

@kddnewton I think it probably falls on @eregon and I to tease out the ramifications of lazy methods.   Right now JRuby also does not raise a syntax error until compile(IR build) time and with lazy methods we potentially will continue executing a Ruby file that MRI will not compile if we never try and call the problem method.  So far no one has ever complained about this.

If someone does figure out a reasonable reason why we need this I personally don't think it will be onerous to walk soft scopes (blocks, for, BEGIN/END) up to a hard scope (script, module/class, method) to emit the error during parse.  It seems fairly conceptually simple to add.  Perhaps we should just wait and see?

**Comment by kddnewton** [comment]
I think I'm okay to reopen and support this if someone can give me explicitly concrete rules on when each of these keywords is valid and invalid. Looking at the CRuby source it's exceedingly unclear to me when they're allowed and when they're not. At the moment, this issue is just too ambiguous.

**Comment by enebo** [comment]
@kddnewton I don't feel the need at this point but I think we could open another issue if the issue gets raised by something real.  

My take is that you would only see this writing a new app and only before you actually tried calling the method containing the mistake.  The notion this would ever make it into anything released would mean people are releasing/deploying methods they have never called before.  Just seems really unlikely.

Another argument is I think we could argue when this error is raised could be undefined behavior.  If MRI decides to do lazy methods (which honestly they should) then I suspect their behavior will be like how we do lazy methods.

**Comment by enebo** [comment]
HAHAH yeah.  Amazing.  I wonder if he read this issue or it is just a coincidence?

**Comment by kddnewton** [comment]
Not sure!
