### ISSUE TITLE
Is ArgumentsNode needed?

### ISSUE THREAD

**Issue by eregon** [ruby/yarp#933]
I noticed it's just:
```java
    public static final class ArgumentsNode extends Node {
        public final Node[] arguments;
```
So maybe we could just have the Node[] in the parent node? (to save the allocation and footprint)

Although I guess one thing it provides is the start & end offsets of arguments, but maybe that can be computed simply from the `nodes[0].start` and `nodes[-1].end`?

**Comment by eregon** [comment]
(sorry I accidentally created this issue before filling the description, now it has a proper description)

**Comment by enebo** [comment]
One mildly annoying thing right now is I cannot args[-1] to check for kwargs since a blockarg may be last arg.  Your suggestion does not address that and perhaps it is not important but it is one possible reason why a node could be useful?

**Comment by enebo** [comment]
@eregon This would be simpler. JRuby currently does not pass keywordarg as a separate operand to call (it is still tacked on as last argument) but we will be doing a large change to keywords soon and this will be separated out (at least when it is known statically).

A second part to this would be to not have blocknode be its own field on callnode but have it share blockArgument.  Block processing right now requires looking at last arg and blockArgument.

The only wrinkle is next/break/return current accept ArgumentsNode but it is impossible to have a blockArgument.  It can just be null or it could NonlocalFlowControlArgumentsNode (this is a Java joke).

**Comment by kddnewton** [comment]
It saves on allocations, because if you don't have arguments to something (pretty common) then we don't allocate the space necessary for the array. The node is just null. Also as Tom says, it's used in places where you can't have a block. I think let's keep it for now unless it becomes a problem.

**Comment by eregon** [comment]
Yeah, it's fine, not causing problems.

WDYT of https://github.com/ruby/yarp/issues/933#issuecomment-1572135641 ?
I think separating keywordArguments clearly like that would be valuable, AFAIK that is always known statically.
(there is `ruby2_keywords`, but that a completely separate concern from parsing)

**Comment by kddnewton** [comment]
Maybe. I opened a PR here: https://github.com/ruby/yarp/pull/1243. I'm not sure if it's going to end up being worth adding the extra pointer to every argument node, because that's a lot of bytes. I'll do some measurement next week.

**Comment by enebo** [comment]
@kddnewton Another idea to consider is perhaps is multiple Argument types.  From an implementers standpoint The base type would be what all things have arguments with multiple additional types adding the missing things (or combinations).   From an API standpoint all types would have the same signatures but would return null for things they do not have.  This would save memory overall but also give us separation for keywords (and I would also like to see block + block pass consolidated as they are different representations of the same concept and I consider them both to be arguments).

In JRuby we have use multiple types just to save memory since types are effectively free from cost but we can just define boilerplate return values to represent missing data.  

In C this may lead to a more complicated impl for each value we want out of arguments but it would just be an extra swtich on types that have info with default returning null.

**Comment by enebo** [comment]
Another interesting plus for Java consumers is method overloading would make processing these different argument types not even require conditionals.  Most method calls are regular params with no opt, no rest, no kws, no block.  I am implying a lot more possible complexity here; but I am not saying we should add it just that it gives a pretty simple path for implementation and it could lead to more sophisticated argument types.

**Comment by eregon** [comment]
@enebo Just to clarify, I'm only talking about ArgumentsNode here (caller side), not ParametersNode, which already separates every kind of parameter nicely.

Virtual calls may look nice but they have a measurable cost performance-wise and I'm pretty sure a single node type is faster, and of course it's so much simpler.

It's true that if no kwargs it adds an extra pointer in the C struct (8 bytes), 1 byte serialized and 4 bytes in Java.
I think this is highly worth it because semantically there are 3 kinds of arguments (positional, keyword, block) and having them clearly separated seems so much nicer to process the AST than `if arguments[-1].is_a? KeywordHashNode`

**Comment by enebo** [comment]
@eregon yeah I did conflate arguments with parameters there but the general concept still holds.  

For performance that is true but I am unsure if it matters.  The problem I have atm is that with the existing parser (e.g. JRuby parser) nothing optimizes past simple C1 stage in hotspot.  The overall shadow of being so cold during parse made all other build things not matter (so space saving techniques had no measurable effect on performance).   With YARP this may be more relevant or not.  You are right though.  It is faster to have a single simple node type.

Memory is the still something we should consider but even that is up in the air with YARP since we may be saving the serialized blob of the memory entry (+ constant pool).  If so then that makes the AST truly transient in JRuby so we only case about the size of the blob + IR.  If we do not end up with that then AST size becomes a concern again.  I am optimistic we can save blobs for method entries and in that case the size of serialized output gets the size focus.

My prediction is that we will see little performance difference on short runs because things tend to not run long enough to optimize much.  pgo and rehearsals for things like CRUI/SVM/Quarkus could make a difference here though?  Not sure.

I think we should take this to a discussion if we care to continue.
